### ISSUE TITLE
demo如果修改为异步方式则会出现函数已被释放问题

### ISSUE THREAD

**Issue by flamefox** [waitingsong/node-win32-api#1]
将最后的消息循环改成如下代码,则会出现问题
```javascript
function loop() {

    // message loop
    const msg = new Struct(DS.MSG)();
    const point = new Struct(DS.POINT)();

    msg.pt = point.ref();

    let count = 0;
    const countLimit = 200;
    const start = new Date().getTime();
    const ttl = 30; // sec
    user32.GetMessageW(msg.ref(), null, 0, 0)
    user32.TranslateMessageEx(msg.ref());
    user32.DispatchMessageW(msg.ref());

    setTimeout(() => {
        loop();
    }, 20);
}

loop();
```

```log
Error: ffi fatal: callback has been garbage collected!
    at Object.proxy [as DispatchMessageW] (E:\dev\nodesrc\testWin\node_modules\ffi\lib\_foreign_function.js:59:14)
    at loop (E:\dev\nodesrc\testWin\index.js:94:12)
    at Timeout.setTimeout [as _onTimeout] (E:\dev\nodesrc\testWin\index.js:96:9)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

**Comment by flamefox** [comment]
It's FFI's BUG see this:https://www.bountysource.com/issues/26683875-ffi-function-underlying-callback-is-garbage-collected

**Comment by waitingsong** [comment]
试试这个：
```js
process.on('exit', () => {
    loop; // keep reference avoid gc
});
```

**Comment by githoniel** [comment]
check https://github.com/node-ffi/node-ffi/issues/84
```
const WndProc = ffi.Callback(........)
process.on('exit', () => {
    WndProc // keep reference avoid gc
});
```

it work in my project
